name: Build

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: "0 19 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: lilac
    concurrency:
      group: lilac
    steps:
      - name: Trigger lilac build
        run: lilac
      - name: Show build result
        run: tail ~/.lilac/build.log
