name: Build

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: "0 19 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: lilac
    concurrency:
      group: lilac
    steps:
      - name: Trigger lilac build
        run: lilac
      - name: Print lilac latest logs
        run: ~/.local/bin/lilac-latest-log
      - name: Show recent build results
        run: tail ~/.lilac/build.log
      - name: Is there any failed build?
        run: ~/.local/bin/lilac-result
